# Generated by Django 5.0.7 on 2024-07-14 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_product_description_alter_product_inventory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Collection",
            new_name="Collection1",
        ),
    ]
